# Generated by Django 3.1 on 2020-09-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_apply', '0002_application_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='income',
            field=models.CharField(choices=[('low', '1000-10000'), ('med', '10001-20000'), ('high', '20001-40000'), ('vhigh', '40001-60000'), ('vvhigh', '60001+')], default='low', max_length=15),
        ),
    ]
